# Generated by Django 5.2.1 on 2025-08-12 17:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['-date_awarded']},
        ),
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='simulation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='achievement',
            name='code',
            field=models.CharField(blank=True, help_text='Código único da conquista (ex: FIRST_WIN).', max_length=100),
        ),
        migrations.AddField(
            model_name='attempt',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='response_choice',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='attempt',
            name='score_delta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attempt',
            name='user_agent',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='simulation',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='choices',
            field=models.JSONField(blank=True, help_text='Estrutura JSON com as opções apresentadas (se aplicável).', null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='correct_choice',
            field=models.CharField(blank=True, help_text="Identificador da opção correta (ex.: 'opcao_a' ou texto).", max_length=200),
        ),
        migrations.AddField(
            model_name='simulation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simulation',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Médio'), ('hard', 'Difícil')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='simulation',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='simulation',
            name='type',
            field=models.CharField(choices=[('email', 'Email'), ('site', 'Site')], default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.simulation'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
