# Generated by Django 5.2.1 on 2025-08-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_module_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Funcionário'), ('admin_ti', 'Administrador de TI')], default='employee', max_length=20),
        ),
    ]
