# Generated by Django 5.2.1 on 2025-08-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Funcionário'), ('admin_ti', 'Admin TI')], default='employee', max_length=20),
        ),
    ]
